_extends: .github

repository:
  name: discord-bot-boilerplate
  description: "A boilerplate for my bots"
  private: false
  is_template: true

branches:
  - name: main
    protection:
      required_status_checks:
        checks:
          - context: CodeQL Analysis
          - context: Test Build
          - context: ESLint
          - context: Jest
          - context: NJS Scan
          - context: OSSAR Analysis
          - context: DeepScan
