version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:eec169935ffe7e62eff1162e1225230bb9d6f5ceb333ab92fccdcf2d198c10f2
    restart: always
    volumes:
      - ./database:/data/db
