version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:d5e5467d15233588a475c2db352bdbd704ef9c8a462c88958b5c91cd7ce60e34
    restart: always
    volumes:
      - ./database:/data/db
