version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:5a6ee5442e8f04f85d6d59133a7a2ac6a664402721f24cfc006483941cb73040
    restart: always
    volumes:
      - ./database:/data/db
