version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:9983b477f443533a06dd85201f1028b313db6ff9568ec687745278fcad80f929
    restart: always
    volumes:
      - ./database:/data/db
