version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:44ab443d63b8bf211ead7c8ff5ffe481820e118bca33d970c626cfc38094aaef
    restart: always
    volumes:
      - ./database:/data/db
