version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:033255f596fb18ee947fabef1377f666f96ff0c0328242a7ff219c284537a76f
    restart: always
    volumes:
      - ./database:/data/db
