version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:17330999a8d1e2f8d1805596c48a7dab5265d8da36ac4de20a5c35c32ea2d6b8
    restart: always
    volumes:
      - ./database:/data/db
