version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:0fa6dcb77614be58740df12231788202887d08ec8c68758e3737d3ddf24035b4
    restart: always
    volumes:
      - ./database:/data/db
