version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:becc9cfff9de203e208194f649042b0396906d45b559d94d418a8cec70f7ad79
    restart: always
    volumes:
      - ./database:/data/db
