version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:3777a245be16fc51c13169d4655013c472ef439f607e9f7850edb0d98a4e9f7d
    restart: always
    volumes:
      - ./database:/data/db
