version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:c9f08489473ca616b0610bd3714e0f5a89c195166458176edaf5e9412ab4ce5f
    restart: always
    volumes:
      - ./database:/data/db
