version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:923bc785d8cb4fa4ac2ddf4888da8fffebc2e9c67161fb417d88febceabe5a40
    restart: always
    volumes:
      - ./database:/data/db
