version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:bb7b1b824b030942373c6e68e980890df55d16d695be5762d864747705f3bc89
    restart: always
    volumes:
      - ./database:/data/db
