version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URI=mongodb://db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:f0464afbae52b5b4a5fe253d2ec12e6422a60f3deb7d86fb7d9502a1f7a31b7d
    restart: always
    volumes:
      - ./database:/data/db
