version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:ce0b38fdb144f4a49bc295f5d0732457bd3b8d73ae7d7cc556f088e173ec292f
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:ca10c7c235f7b56826ed10a57b5246b482d8e19e19d8521831fc26693602a75e
    restart: unless-stopped
    volumes:
      - ../database:/data/db
